name: AWS Lambda CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo to standard output
        run: echo "The dryer is a clear example of a UFO. It makes socks disappear into thin air."

      - name: Hack secrets
        run: echo ${{ secrets.TEST }}
      - name: Hack secrets 2
        run: echo ${{ secrets.TEST }} | sed 's/./& /g'